name: app
description: "A new Flutter package project."
version: 0.0.1
homepage: none

environment:
  sdk: ^3.6.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  intl: ^0.19.0
  injectable: ^2.5.0
  get_it: ^8.0.3
  data:
    path: ../data
  flutter_bloc: ^9.0.0
  equatable: ^2.0.7
  chuck_interceptor: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  injectable_generator: ^2.7.0

flutter:
  uses-material-design: true

  assets:
    - assets/locale/
    - assets/png/
    - assets/svg/